### ISSUE TITLE
Provide UuidMixin for consistent use of UUIDs as non-primary keys

### ISSUE THREAD

**Issue by jace** [hasgeek/coaster#123]
Several of our apps have evolved use of UUIDs, but in their own ways:

1. [ ] DocTypeHTML5 began the tradition of using Base64 UUIDs, but with a custom alphabet.
2. [ ] Lastuser introduced them as the `userid` column, also standardising on URL-safe Base64 encoding, henceforth known as the `buid` encoding.
3. [ ] Eventframe uses `buid` encoding in a column named `uuid`.
4. [ ] Nodular uses `buid` encoding in a column named `buid`.
5. [ ] Imgee uses hex encoding in a column named `name`.
6. [ ] Hasjob uses native UUID storage for the session object, in a column named `uuid`.

These varied usages need to be standardised. While `IdMixin` introduced support for UUID primary keys in 1d2d315c5ab216d93ab87faa353399026799af06, we have many cases where the app is not ready to migrate to UUIDs for primary keys, and only needs them for secondary (but unique) keys.

Following the lessons from #112, #114 and #121, we could introduce a `UuidMixin` that offers a standard interface:

1. [ ] A `uuid` column that stores a native UUID and auto-generates it on first access (as in #112 for IdMixin).
2. [ ] A `buid` hybrid attribute that proxies to the native UUID storage (as in #114).
3. [ ] An `suuid` hybrid attribute that does likewise (as in #121).
4. [ ] Optional: a `url_id` hybrid attribute (as in #114).

The hybrid attributes in this `UuidMixin` will clash with the ones provided by `IdMixin` in #121. The assumptions for use therefore are:

1. A class using `UuidMixin` gives it priority by using the `UuidMixin, BaseMixin, db.Model` order for base classes.
2. This class must _not_ use UUID primary keys.
3. Migrations (database and code references) will be necessary for each of the apps listed above.

**Comment by jace** [comment]
The implementation in #124 uses `@declared_attr` to make `uuid` a column if the main class uses integer primary keys, else an alias to the existing `id` UUID column.
